name: 'Setup Development Environment'
description: 'Sets up Python, Rust, and uv for the merge-sat project'

inputs:
  python-version:
    description: 'Python version to set up'
    required: false
    default: '3.13'
  rust-components:
    description: 'Rust components to install (comma-separated)'
    required: false
    default: ''
  cache-key-suffix:
    description: 'Additional suffix for cache keys'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v4

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: ${{ inputs.rust-components }}

    - name: Setup Rust cache
      uses: Swatinem/rust-cache@v2
      with:
        key: ${{ inputs.cache-key-suffix }}

    - name: Install Python dependencies
      shell: bash
      run: |
        echo "Syncing Python dependencies..."
        uv sync --all-packages
