name: Documentation

on:
  push:
    branches: [ main, master ]
    paths:
      - 'rs/**/*.rs'
      - 'py/**/*.py'
      - 'README.md'
      - 'tex/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'rs/**/*.rs'
      - 'py/**/*.py'
      - 'README.md'
      - 'tex/**'

jobs:
  # Build Rust documentation
  rust-docs:
    name: Build Rust Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup development environment
        uses: ./.github/actions/setup-dev-env
        with:
          cache-key-suffix: 'rust-docs'

      - name: Build documentation
        run: cargo doc --all --no-deps

      - name: Check for broken intra-doc links
        run: cargo doc --all --no-deps
        env:
          RUSTDOCFLAGS: "-D warnings"

  # Build Python documentation (if you add sphinx later)
  python-docs:
    name: Check Python Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup development environment
        uses: ./.github/actions/setup-dev-env
        with:
          cache-key-suffix: 'python-docs'

      - name: Check docstrings
        run: |
          # Check that all Python modules have proper docstrings
          find py -name "*.py" -exec python -c "
          import ast
          import sys
          with open('{}', 'r') as f:
              tree = ast.parse(f.read())
              if not ast.get_docstring(tree):
                  print('Missing module docstring in: {}')
                  sys.exit(1)
          " \;

  # Build LaTeX documentation
  latex-docs:
    name: Build LaTeX Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: tex
          root_file: muffler.tex
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: research-paper
          path: tex/muffler.pdf
