name: Security and Dependencies

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:
  push:
    paths:
      - 'Cargo.toml'
      - 'Cargo.lock'
      - 'pyproject.toml'
      - 'uv.lock'

jobs:
  # Rust security audit
  rust-security:
    name: Rust Security Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup development environment
        uses: ./.github/actions/setup-dev-env
        with:
          cache-key-suffix: 'rust-security'

      - name: Install cargo-audit
        uses: taiki-e/install-action@cargo-audit

      - name: Run cargo audit
        run: cargo audit

  # Python security check
  python-security:
    name: Python Security Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup development environment
        uses: ./.github/actions/setup-dev-env
        with:
          cache-key-suffix: 'python-security'

      - name: Run safety check
        run: uv run pip-audit

  # Dependency review (only on PRs)
  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/dependency-review-action@v4
